spring.application.name=SistemaCrud

spring.datasource.url=jdbc:postgresql://localhost:5432/CRUD_API
spring.datasource.username=usuario_exemplo
spring.datasource.password=senha_exemplo

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.flyway.enabled=true

app.security.admin.username=admin
app.security.admin.password=admin123
app.security.professor.username=professor
app.security.professor.password=professor123
app.security.aluno.username=aluno
app.security.aluno.password=aluno123
