spring.application.name=SistemaCrud

spring.datasource.url=jdbc:postgresql://localhost:5432/CRUD_API
spring.datasource.username=postgres
spring.datasource.password=posthabbgres16

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



